/** @type {Special.Item[]} */
const outputRemoved = [
  "#mekanism:clumps",
  "#mekanism:dirty_dusts",
  "#mekanism:shards",
  "ae2:calculation_processor",
  "ae2:charged_certus_quartz_crystal",
  "ae2:engineering_processor",
  "ae2:fluix_crystal",
  "ae2:inscriber",
  "ae2:logic_processor",
  "ae2:printed_calculation_processor",
  "ae2:printed_engineering_processor",
  "ae2:printed_logic_processor",
  "ae2:printed_silicon",
  "ars_nouveau:agronomic_sourcelink",
  "ars_nouveau:alchemical_sourcelink",
  "ars_nouveau:arcane_core",
  "ars_nouveau:arcane_pedestal",
  "ars_nouveau:belt_of_unstable_gifts",
  "ars_nouveau:enchanting_apparatus",
  "ars_nouveau:glyph_randomize",
  "ars_nouveau:imbuement_chamber",
  "ars_nouveau:lava_lily",
  "ars_nouveau:mob_jar",
  "ars_nouveau:source_gem",
  "ars_nouveau:source_jar",
  "ars_nouveau:sourcestone",
  "ars_nouveau:vitalic_sourcelink",
  "ars_nouveau:volcanic_sourcelink",
  "botania:alchemy_catalyst",
  "botania:conjuration_catalyst",
  "botania:entropinnyum",
  "botania:fertilizer",
  "botania:mana_spreader",
  "botania:orechid",
  "botania:rune_air",
  "botania:rune_autumn",
  "botania:rune_earth",
  "botania:rune_fire",
  "botania:rune_spring",
  "botania:rune_summer",
  "botania:rune_water",
  "botania:rune_winter",
  "botania:runic_altar",
  "brickhopper:brick_hopper",
  "cookingforblockheads:sink",
  "create:blaze_cake",
  "create:empty_blaze_burner",
  "create:precision_mechanism",
  "createaddition:biomass",
  "createaddition:cake_base_baked",
  "createaddition:cake_base",
  "createaddition:electric_motor",
  "functionalstorage:oak_1",
  "functionalstorage:oak_2",
  "functionalstorage:oak_4",
  "functionalstorage:puller_upgrade",
  "functionalstorage:pusher_upgrade",
  "industrialforegoing:fluid_laser_base",
  "industrialforegoing:laser_drill",
  "industrialforegoing:latex_processing_unit",
  "industrialforegoing:machine_frame_pity",
  "industrialforegoing:ore_laser_base",
  "industrialforegoing:plastic",
  "mekanism:crafting_formula",
  "mekanism:formulaic_assemblicator",
  "mekanism:steel_casing",
  "minecraft:end_crystal",
  "minecraft:ender_pearl",
  "minecraft:netherite_scrap",
  "naturesaura:gold_fiber",
  "naturesaura:offering_table",
  "naturesaura:projectile_generator",
  "naturesaura:tainted_gold_block",
  "naturesaura:tainted_gold",
  "powah:dielectric_paste",
  "powah:energy_cable_starter",
  "powah:photoelectric_pane",
  "powah:reactor_nitro",
  "powah:solar_panel_starter",
  "reliquary:alkahestry_tome",
  "starbunclemania:fluid_sourcelink",
  "thermal:charcoal_block",
  "thermal:chiller_ball_cast",
  "thermal:chiller_ingot_cast",
  "thermal:chiller_rod_cast",
  "thermal:device_nullifier",
  "thermal:device_rock_gen",
  "thermal:dynamo_stirling",
  "thermal:enderium_dust",
  "thermal:enderium_ingot",
  "thermal:lead_ingot",
  "thermal:lumium_dust",
  "thermal:lumium_ingot",
  "thermal:machine_chiller",
  "thermal:machine_crafter",
  "thermal:machine_crucible",
  "thermal:machine_frame",
  "thermal:machine_furnace",
  "thermal:machine_pulverizer",
  "thermal:machine_smelter",
  "thermal:machine_speed_augment",
  "thermal:phytosoil",
  "thermal:redstone_servo",
  "thermal:rf_coil",
  "thermal:signalum_dust",
  "thermal:signalum_ingot",
  "thermal:silver_ingot",
  "thermal:tin_ingot",
  "thermal:upgrade_augment_1",
  "thermal:upgrade_augment_2",
  "thermal:upgrade_augment_3",
  "tiab:time_in_a_bottle",
];

/** @type {Special.Item[]} */
const inputRemoved = ["minecraft:raw_gold_block", "minecraft:netherite_block"];

/** @type {Special.Item[]} */
const inputOutputBothRemoved = [
  "create:crushed_raw_gold",
  "create:crushed_raw_iron",
  "create:zinc_ingot",
  "create:zinc_nugget",
  "minecraft:gold_ore",
  "minecraft:iron_ore",
  "minecraft:lapis_ore",
  "minecraft:raw_gold",
  "minecraft:raw_iron",
  "minecraft:target",
  "supplementaries:lapis_bricks",
];

/** @type {Special.RecipeId} */
const idRemoved = [
  "create:crushing/redstone_ore",
  "industrialforegoing:dissolution_chamber/advanced_machine_frame",
  "industrialforegoing:dissolution_chamber/simple_machine_frame",
  "industrialforegoing:dissolution_chamber/supreme_machine_frame",
  "industrialforegoing:fluid_extractor/default",
  "mekanism:processing/lategame/polonium_pellet/from_reaction",
  "mekanism:processing/redstone/from_ore",
  "naturesaura:tree_ritual/nature_altar",
  "thermal:machines/chiller/chiller_ender_to_ender_pearl",
  "thermal:machines/chiller/chiller_glowstone_to_glowstone_block",
  "thermal:machines/chiller/chiller_redstone_to_redstone_block",
  "thermal:machines/crucible/crucible_cobblestone_to_lava",
  "thermal:machines/crucible/crucible_ender_pearl",
  "thermal:machines/crucible/crucible_glowstone_block",
  "thermal:machines/crucible/crucible_glowstone_dust",
  "thermal:machines/press/packing3x3/press_raw_iron_packing",
  "thermal:machines/press/press_bronze_ingot_to_coin",
  "thermal:machines/press/press_bronze_nugget_to_coin",
  "thermal:machines/press/press_constantan_ingot_to_coin",
  "thermal:machines/press/press_constantan_nugget_to_coin",
  "thermal:machines/press/press_copper_ingot_to_coin",
  "thermal:machines/press/press_copper_nugget_to_coin",
  "thermal:machines/press/press_electrum_ingot_to_coin",
  "thermal:machines/press/press_electrum_nugget_to_coin",
  "thermal:machines/press/press_enderium_ingot_to_coin",
  "thermal:machines/press/press_enderium_nugget_to_coin",
  "thermal:machines/press/press_gold_ingot_to_coin",
  "thermal:machines/press/press_gold_nugget_to_coin",
  "thermal:machines/press/press_invar_ingot_to_coin",
  "thermal:machines/press/press_invar_nugget_to_coin",
  "thermal:machines/press/press_iron_ingot_to_coin",
  "thermal:machines/press/press_iron_nugget_to_coin",
  "thermal:machines/press/press_lead_ingot_to_coin",
  "thermal:machines/press/press_lead_nugget_to_coin",
  "thermal:machines/press/press_lumium_ingot_to_coin",
  "thermal:machines/press/press_lumium_nugget_to_coin",
  "thermal:machines/press/press_netherite_ingot_to_coin",
  "thermal:machines/press/press_nickel_ingot_to_coin",
  "thermal:machines/press/press_nickel_nugget_to_coin",
  "thermal:machines/press/press_signalum_ingot_to_coin",
  "thermal:machines/press/press_signalum_nugget_to_coin",
  "thermal:machines/press/press_silver_ingot_to_coin",
  "thermal:machines/press/press_silver_nugget_to_coin",
  "thermal:machines/press/press_tin_ingot_to_coin",
  "thermal:machines/press/press_tin_nugget_to_coin",
  "thermal:machines/press/unpacking/press_netherite_unpacking",
  "thermal:machines/press/unpacking/press_raw_iron_unpacking",
  "thermal:machines/pulverizer/pulverizer_cobblestone",
  "thermal:machines/pulverizer/pulverizer_gold_ore",
  "thermal:machines/pulverizer/pulverizer_iron_ore",
  "thermal:machines/pulverizer/pulverizer_lapis_ore",
  "thermal:machines/pulverizer/pulverizer_raw_gold",
  "thermal:machines/pulverizer/pulverizer_raw_iron",
  "thermal:machines/pulverizer/pulverizer_redstone_ore",
  "thermal:machines/smelter/smelter_alloy_enderium",
  "thermal:machines/smelter/smelter_alloy_lumium",
  "thermal:machines/smelter/smelter_alloy_signalum",
  "thermal:machines/smelter/smelter_gold_ore",
  "thermal:machines/smelter/smelter_iron_ore",
  "thermal:machines/smelter/smelter_raw_gold",
  "thermal:machines/smelter/smelter_raw_iron",
  "thermal:machines/smelter/smelter_redstone_ore",
];

ServerEvents.recipes((event) => {
  event.remove({ input: inputRemoved });
  event.remove({ output: outputRemoved });

  event.remove({ input: inputOutputBothRemoved });
  event.remove({ output: inputOutputBothRemoved });

  idRemoved.forEach((recipeId) => event.remove({ id: recipeId }));

  event.remove({ output: "minecraft:netherite_block", type: "minecraft:crafting_shaped" });
  event.remove({ output: "minecraft:netherite_ingot", type: "minecraft:crafting_shapeless" });

  event.remove({ mod: "occultism" });

});
